### ISSUE TITLE
Weird PSFs

### ISSUE THREAD

**Issue by tibuch** [bene51/SPIM_Reconstruction_Cuda#1]
Hi @bene51 

I am working with your Fiji-Plugin.
I performed a DoG (sigma = 2, threshold = 0.3) on single channel for the bead based registration and then transformed it with Cuda Transform from your plugin.

Then i extracted the PSFs.
![psfs](https://cloud.githubusercontent.com/assets/5450869/8077543/ed09b282-0f56-11e5-8787-6b82384d8e74.png)

These PSFs produce some line artifacts (with 2-3 iterations) in my deconvolved image. 

I also replaced the extracted PSFs with the PSFs from the Preibisch Multiview-Deconvolution (they are more point like). With the Preibisch PSFs I get some better results.

**Comment by bene51** [comment]
Hi @tibuch 

thanks for reporting. Is there any chance you could share your data?

Extract_PSF_Planes is merely a wrapper around Preibisch's Multiview Deconvolution plugin, to extract the PSFs. So the same results should be obtained. Can you check that the parameters match the ones you use:

https://github.com/bene51/SPIM_Reconstruction_Cuda/blob/master/src/main/java/fastspim/Extract_PSF_Planes.java#L97

Best,
Bene

**Comment by bene51** [comment]
Just to finish this:
PSFs are saved as raw data in 32-bit floating point format in Intel byte order. To open them with Fiji, one needs to choose '32-bit Float' for 'Image type'.
